### ISSUE TITLE
Issueベースの開発_レビュー依頼

### ISSUE THREAD

**Issue by emahji2683** [emahji2683/ArtVibe#31]

**Comment by emahji2683** [comment]
### ■Webアプリの概要
### 本サービスの概要

ユーザーが美術館に関する情報を共有し、おすすめの美術館を発見できるアプリです。メイン写真とサブ写真を用いたカード形式で投稿ができ、レビューや周辺のカフェ情報も提供します。AIによるレコメンド機能で、ユーザーの好みに応じた美術館も提案されます。

#### このサービスへの思い・作りたい理由

趣味で美術館を巡っている中で、訪れた美術館の情報を記録し共有したいという思いがありました。また、地図サービスに不足している詳細情報を補い、美術館好きが集うコミュニティを作りたいと考えています。友人からのおすすめ美術館に行った経験から、他の人の推し美術館を知ることの楽しさにも気付き、このサービスに活かしたいと考えました。また、現地でしか得られない周辺情報もまとめ、ユーザーの利便性を高めたいと感じています。

#### ユーザー層について

美術館を頻繁に訪れる人を主なターゲットとしています。美術館巡りを趣味としている人は全体の約10％とされ、ニッチであるものの、特化したニーズに応えることで、レビューサービスとの差別化が図れると考えています。国立アートリサーチセンターの統計を参考に、美術館好きに訴求するアプリを目指しています。

#### サービスの利用イメージ

- 多様なユーザーが訪れた美術館の投稿を閲覧し、行ってみたい場所への興味をかき立てます。投稿には、写真や紹介文、基本情報が含まれ、いいね機能で共感を示すことができます。
- 自分の推し美術館を写真付きで投稿し、他のユーザーと情報を共有します。
- 美術館を「展示内容」「施設」「入場料の価値」など多面的に評価でき、利用者はより深い情報を得られます。
- 特定の美術館周辺のカフェ情報も合わせて表示し、鑑賞後の時間も充実させます。
- 来訪やいいねの履歴をもとに、AIが好みに合う美術館を提案し、効率的な美術館探しを支援します。

#### ユーザーの獲得について

美術館好きユーザーは訪問経験が豊富で、他者におすすめしたいスポットを知っている可能性が高いです。このようなユーザーが自身の推しポイントを表現できるよう、外観写真や周辺施設情報を詳細に掲載できる設計とします。また、評価軸を統計的な根拠を持たせることで、より信頼性の高い評価が得られることを意識しています。

#### サービスの差別化ポイント・推しポイント

- 美術館好きに特化しているため、興味が薄いユーザーによる評価が排除され、専門性の高いレビューが得られます。
- 美術館に関する多角的な評価が可能で、展示のテーマや施設の快適さ、入場料の価値など詳細な情報を提供します。
- 入場料の比較機能により、他美術館との費用対効果を表示し、コストパフォーマンスの良い美術館が探しやすくなります。
- カフェやショップ情報も追加し、美術鑑賞前後の楽しみも提案します。

### ■1週間辺りの開発に向けられる時間
- 1週間あたり：40時間

（ストーリポイント1消費するのに2時間を目安として、1週間あたりどれだけストーリポイントを消化できるか確認してください）

### ■ProjectsのURL
``作成したProjects（看板・issue・ストーリーポイントが確認できるもの且つ他者でも閲覧可能状態）のURLを貼り付けてください。``
https://github.com/users/emahji2683/projects/3

### ■MVPリリースまで
- [×] rails new
- [×] Herokuにデプロイ
- [×] トップページ
- [×] 新規ユーザーの作成機能
- [×] ユーザーログイン機能
- [×] ユーザーログアウト機能
- [×] 美術館レビュー作成機能
- [×] 美術館レビュー編集機能
- [×] 美術館レビュー削除機能
- [×] 美術館検索機能
- [×] 美術館いいね機能
- [×] 画像投稿機能(プロフィールアバター、美術館レビュー)


### ■MVP後

- [×] 動的OGP 
- [×] 生成AIによるレコメンド
- [×] ランキングシステム、カフェの表示機能
- [×] 地図上への表示
- [×] 利用規約
- [×] プライバシーポリシー
- [×] お問い合わせ
- [×] RSpec（モデルテスト・システムテスト）
- [×] CI（GitHubActions）
- [×] ファビコン
- [×] 独自ドメイン

### ■MVPレビュー依頼予定日
予定日：2024年 12月 20日

**Comment by kenchasonakai** [comment]
LGTMです！
