### ISSUE TITLE
MVPリリース

### ISSUE THREAD

**Issue by emahji2683** [emahji2683/ArtVibe#68]
## 各種情報
サービスの概要とMVPで検証する事柄：ログイン、ログアウト、検索、オートコンプリート、画像投稿
サービス名：ArtVibe
サービスURL：https://artvibe-qd4d.onrender.com/

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [x] アカウント登録 
- [x] オートコンプリート機能
- [x] 非同期通信(美術館検索のオートコンプリート)
- [x] カードの検索機能
- [x] 画像投稿機能

READMEレビュー時に実装予定だった機能が実装できているかがわかるように記載してください。

## READMEレビュー時から変更した機能
特になし

## サービスイメージがわかるようなスクリーンショット等
特になし

**Comment by busitora** [comment]
## 全般

- パスワードやアドレスのinput要素にフォーカスあてないとわからないのは直したほうがいいですね。すべてのformで直したほうが良さそうです。
<img width="278" alt="スクリーンショット 0006-12-02 20 56 37" src="https://github.com/user-attachments/assets/75a747a0-9e2e-4ae5-b909-6b45e0f44c88">

- 中央寄せやCSSはレビューしないでおきますね。
- エラーメッセージがi18n化されていないケースがあるようでした。ログイン失敗時に発生しました。

## 画像投稿機能

- 最大3枚とありますが、サブ写真が複数選択できませんでした。
- 投稿したreviewに対するリンクがなく、どこに投稿したかわかるようにしたほうがいいですね。

## その他
下記についてはよくわからなかったので、Gyazoのgif動画等を使いイメージ動画を概要欄に記載してください。

-  オートコンプリート機能
-  非同期通信(美術館検索のオートコンプリート)

**Comment by TakenakaEri** [comment]
機能確認が取れました。LGTMです。
引き続き本リリースに向けて開発頑張ってください。

以下、LGTMを出した方々に共通してお伝えしている内容になります。
（Webアプリを就職活動で活用される方向けの内容になります）

===== 本リリースまでに以下の項目を実装してください =====
□ 独自ドメイン反映
    -> DNSやSSLの対応も必要になるのでアピールになり、URLを書類等に記載するときの見栄えも良くなります。
□ OGP（静的 or 動的）
    -> SNS等でシェアするときの見栄えが良くなります。Webアプリであればどんなアプリでも取り入れられるので対応しておきましょう。
□ RSpec（モデルテスト+システムテスト or モデルテスト+リクエストテスト）
    -> 開発における品質の意識や開発効率の意識の高さをアピールできます。Request Specをメインに最低限各機能に正常にアクセスできるか程度はテストで確認できるようにしておきましょう。
□ CI（GitHubActions）
    -> 実際に開発現場でも使われており、アプリ外で技術のアピールが出来るものです。RSpecと合わせて実装を行いましょう。
□ Rubocopを使ってのリファクタリング
    -> Lintチェックツールは開発現場で広く使われています。コードのLintを整えておくことはチームで開発することを意識するうえでとても大切になるので取り入れておきましょう。

他のプログラミング学習者のWebアプリと異なることをアピールするために、よりインパクトのある機能を複数盛り込むことが重要になってきます。
□ SNSログイン（Google or LINE）
    -> ほとんどのアプリに取り入れられてユーザー体験の向上や技術のアピールにつながるので取り入れましょう。
□ 検索機能のアップデート（オートコンプリート、マルチ検索等）   ※検索機能がある場合
    -> 特にオートコンプリートは検索体験の向上だけではなくJS系の技術も取り入れていることをアピール出来るので積極的に取り入れましょう。

ユーザー体験という面では以下の項目も大切です。
□ オートログイン
    -> ユーザー登録後に再度ログイン操作を行わせないことでユーザー体験を向上させられます。
□ 使い方説明がある
    -> 初めて訪れたユーザーに呈して使い方の説明があることで体験を向上させられます。
□ レスポンシブ対応
    -> いずれのデバイスでも綺麗にサービスが活用できることで体験が良くなります。
□ 利用規約・プライバシーポリシーを未ログイン状態でも確認できる
    -> 利用規約・プライバシーポリシーがあることで、ちゃんとしたサービスという印象を与えられます。
□ ローディングアニメーション（処理が重い箇所）
    -> 処理が重い箇所に何の対応も無いとユーザーが正しく操作できたのか困惑してしまいます。そうした際はローディングアニメーションを表示させることで体験が向上します。
